Feature/modi 9 : 보일러 플레이트 추가
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #1
Opened 2021-11-27 08:34 UTC by sirin0762

### 구현 목록
- GlobalExceptionHandler 에 3개의 예외처리를 넣어놨습니다.
  - InternalServerError
  - invalidRequestArgumentError
  - NotFoundError
- 커스텀 NotFoundError를 만들었습니다.
- 에러 응답을 처리할 공통적인 데이터 포멧인 ErrorResponse를 만들었습니다.

### 궁금 사항
- 응답 해더에 http status가 있을 텐데 `ErrorResponse` 에 status를 안넣는게 좋을까요?
- `ErrorResponse` 에 요청 uri를 넣을지 말지 고민하고있습니다. 어떻게 하는게 좋을 까요?

### 그 외
- 제가 두분에 비해서 많이 부족합니다😥 아낌없는 피드백 부탁드리겠습니다!! 감사합니다!!

2021-11-27 09:38 UTC, sangmin7648 requested changes
> 궁금 사항
> 응답 해더에 http status가 있을 텐데 ErrorResponse 에 status를 안넣는게 좋을까요?
> ErrorResponse 에 요청 uri를 넣을지 말지 고민하고있습니다. 어떻게 하는게 좋을 까요?

- 저는 사실 ErrorResponse도 필요한가? 라는 생각이 들긴 하네요. 응답을 어떻게 할지 얘기 나눠봐야할거 같습니다. 티켓 만들어 놓을게요!!!

> 제가 두분에 비해서 많이 부족합니다😥 아낌없는 피드백 부탁드리겠습니다!! 감사합니다!!

로사는 전혀 부족하지 않습니다! 우리팀 최약체는 저에요!!! 오히려 일이 쌓이니 즐거워하시는 모습을 보고 본받고 싶다는 생각이 들었습니다ㅋㅋㅋㅋ

2021-11-27 09:38 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
혹시 이건 무엇을 위한 표시일까요??

2021-11-27 09:38 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(errors);
제가 bean validation을 잘 모르는데요. 저희는 전에 가장 첫번쨰 오류 메시지만 반환하도록 했어서요. 여기처럼하면 뭐가 반환되나요??? @sirin0762  @suhyunsim 알려주세요! 응애! 🤣

2021-11-27 09:38 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/exception/NotFoundException.java
> +}
```suggestion
    public NotFoundException(String message) {
        super(message);
    }
    
}
```
띄어쓰기 불편충 등장 ㅎㅎ

2021-11-28 03:25 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
앗 이것도 여쭤봤어야 했는데 깜빡했네여😅
저는 제가 짠 코드에 이름을 붙이는 것을 좋아해여. 그러면 뭔가 다른사람한태 보여진다는 느낌이 생겨서 더 코드에 대해서 생각하게 된달까... 불필요한 주석이라고 생각되신다면 빼놓겠습니다!!

2021-11-28 03:27 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(errors);
만약 요청 객체에 2개 이상의 validation 오류가 있을 경우, 저렇게 필드명과 오류 메세지를 묶어줘서 받는 쪽에서 알아보기 쉽게 하려했습니다!

2021-11-28 03:28 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/error/exception/NotFoundException.java
> +}
앗 ㅎㅎ 수작업으로 검사했는데 역시 플러그인 설치해야겠네여😂
상민님이 저번에 말하셨던 저장시에 코드 포멧팅 되는 플러그인이 `Save actions` 이것일까요...?
화요일에 플러그인 세팅 맞춰놓으면 좋을것 같아여!!😁😁

2021-11-28 06:15 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
깃으로도 충분히 추적가능한거 같아서 불필요하다고 생각합니다! 혹시 Intellij에 GitToolBox 플러그인이 설치 안되어있다면 해보세요. 코드를 누가 썼는지 편하게 보여줘요.

2021-11-28 06:15 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/exception/NotFoundException.java
> +}
넵 같이 포멧 xml도 설정하면 좋을거 같습니다.!!

2021-11-28 08:29 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
오오 그런기능이 있었군요 ㅎㅎ 그러면 주석처리는 다 지우고 깔아서 확인해보겠습니다!! 감사합니다 ㅎㅎ

2021-11-28 17:06 UTC, suhyunsim requested changes
> 궁금 사항
응답 해더에 http status가 있을 텐데 ErrorResponse 에 status를 안넣는게 좋을까요?
ErrorResponse 에 요청 uri를 넣을지 말지 고민하고있습니다. 어떻게 하는게 좋을 까요?

* 사실 저도 ErrorResponse에 대한 처리를 어떻게 할 지 아직 고민이긴 한데 일단 이 부분은 지난 번 회의 때 의논한 것처럼 우선 프론트팀원 분들과 요청/응답을 어떻게 할 지 확립을 하면서 결정짓는게 좋을 것 같습니다. 최대한 restful 하되 굳이 필요 없는 부분을 넣지는 않는게 가장 깔끔할듯 싶어요!
* 그리고 로켓단 여러분 두분 다 정말 부족함 없으니 걱정 말고 함께 헤쳐나가요. 저는 우리 팀원들 덕분에 든든합니다. 화이팅! 😎

2021-11-28 17:06 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
로이가 잘 말해주셨네요! 저도 주석은 최대한 없애는 쪽으로 가는게 좋을 것 같아요. 한 파일을 팀원이 모두 수정할 일도 있을 수 있고 주석 없이 코드로 충분히 설명될 수 있도록 하는게 가장 바람직한 방향이라고 생각합니다.

2021-11-28 17:06 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> +    }
* 최근에 Apache Commons Lang 3 라이브러리의 여러 기능들을 써보면서 깔끔하고 유용하다는 생각이 들었어요. 이번 프로젝트에 적용해보는건 어떨까요?

> 참고 [예시 링크](https://recordsoflife.tistory.com/474), [공식 문서](https://commons.apache.org/proper/commons-lang/javadocs/api-release/index.html)

* 의존성 추가

```groovy
implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
```

* 적용한 코드
```suggestion
    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE)
            .append("errorMessage", errorMessage)
            .append("requestUri", requestUri)
            .append("status", status)
            .toString();
    }
```

2021-11-28 17:06 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/error/exception/NotFoundException.java
> +}
추가로 파일 마지막에 자동 개행이 되는 것도 설정해주시면 좋을 것 같아요! 개행이 없으면 다른 팀원이 해당 파일을 고치게 될 때 변경 사항이 아니라 새로운 파일로 인식하는 경우가 있다고 하더라고요~

> [링크](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)

2021-11-29 00:43 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> + */
@sangmin7648 @suhyunsim 좋은 피드백 감사합니다!!! 바로 반영할게요!😁😁

2021-11-29 22:40 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> +    }
잭슨의 강의에 나왔던 부분이네요. 저도 보면서 간결해보여 좋다고 생각했습니다. 별도 의존성 추가 없이도 되던데, Spring Starter 어딘가에 의존성이 이미 추가되어 있는걸까요?

2021-11-29 22:41 UTC, sangmin7648 approved these changes

2021-12-01 05:02 UTC, sangmin7648 approved these changes

2021-12-01 05:03 UTC, merged