[MODI-84] 유저 정보 조회 기능 구현
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #13
Opened 2021-12-07 16:20 UTC by suhyunsim

## 유저 정보 조회 API 구현
### 구현한 내용
* 기존 header에 `token` 키로 구현되어있던 jwt token을 Authorization에 `Bearer Token`으로 입력받도록 변경했습니다.
* Swagger 설정에 `Bearer Token`을 입력 받을 수 있도록 추가했습니다.
* 기존에 develop 브랜치에 적용되어있던 `application.yaml` 파일의 내용을 반영했습니다. 추가로 jwt 토큰의 expiry seconds를 172800초로 변경했습니다. (이틀)
* 토큰에 담겨있는 정보와 다른 유저의 정보에 접근하려고 할 때 Forbidden 예외를 발생시키도록 했고 해당 커스텀 예외를 handler에 추가했습니다.
    * 현재 발생하는 Forbidden 예외는 spring security 관련 예외처리가 아니라 컨트롤러에서 단순히 api 엔드포인트에 담겨 있는 userId값을 비교할 때 발생하는 에러입니다. Security 단에서 발생하는 예외(토큰이 없음, 시그니쳐 다름, 토큰 만료 등)들은 Spring 이전에 발생할 것이고 해당 예외에 대한 처리는 `AuthenticationEntryPoint`를 custom implements 하고 해당 컴포넌트를 Security configure 설정에 추가해야 합니다. 그런데 security 관련 예외들을 세세하게 구분해서 예외처리를 하는게 과연 좋을지는 의문입니다. 너무 많은 정보를 예외로 담아서 앞단에 보내는게 아닐까 싶어요!
* 유저 조회 기능은 기존 UserService에 있던 findById 메서드의 리턴 타입을 UserResponse로 변경해서 구현했습니다.
* 유저 정보 조회 테스트를 위해서는 Spring Security 관련 내용이 있어서 `@WithSecurityContext`를 mock으로 구현해서 사용했습니다. 테스트를 위해서 테스트 데이터의 jwt 토큰을 생성하려다가 현재 token에 있는 값을 활용하는 것이 아니라 authentication에 있는 userId를 활용하는 코드로 구현되어 있어서 따로 토큰은 넣지 않았습니다.
* 대신 jwt token이 제대로 생성되는지 확인하기 위해 JwtTest를 추가했습니다.
* 회원가입 후 유저의 정보가 저장될 때 naver의 경우 `OAuth2User`의 providerId에 다른 정보들이 들어가는 것을 방지하기 위한 로직을 추가했습니다.

### 수정되어야 할 부분
* 현재 유저의 이름은 하드코딩된 default로 들어가고 있는데 닉네임 랜덤생성기 내용을 반영해서 수정할 예정입니다.
* birth와 관련한 내용은 kakao가 현재 출생연도를 제공하고 있지 않아서 하드코딩된 1995년으로 저장되고 있습니다. 따로 티켓을 추가해 구현하겠습니다.

> 생각보다 단순한 기능이 너무 오래걸려서 팀원들에게 죄송한 마음 뿐입니다..😭😭 이제 security 관련한 부분은 어느정도 정리되었으니 api 공장 가동하겠습니다...! 여러분의 피드백 언제나 환영합니다!!

2021-12-07 16:22 UTC, suhyunsim commented
현재 충돌나는 부분들은 jwt token 만료시간 변경한 것과 닉네임 랜덤 생성기 내용이라 리뷰 후 바로 수정하겠습니다~

2021-12-07 18:01 UTC, sangmin7648 requested changes
변경 파일 수만 봐도 고생하신게 보입니다 ㅠㅠㅠ 정말정말 수고 하셨어요🤣🤣🤣! 이미 develop에 머지된 사항이 몇몇 보이는데 리베이스를 한번 하시는걸 추천드립니다!

> 그런데 security 관련 예외들을 세세하게 구분해서 예외처리를 하는게 과연 좋을지는 의문입니다
- ForbiddenException이 아니라면 NotFoundException을 던져야할텐데 오히러 개발하면서 프론트한테 혼란을 줄 수 있을거 같아 작성하신 예외가 좋은거 같습니다 

> 현재 유저의 이름은 하드코딩된 default로 들어가고 있는데 닉네임 랜덤생성기 내용을 반영해서 수정할 예정입니다.
- 아래 리뷰 확인 부탁드립니다. 유저 이름은 제가 랜덤 생성기를 만들면서 그것을 이용하도록 수정했었고 현재 develop에도 머지되어 있습니다!!

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/service/UserService.java
> +    public UserResponse findById(Long id) {
현재 dto는 get, 엔티티는 find를 쓰고 있어서 변경되어야할거 같습니다!

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/common/jwt/JwtAuthenticationFilter.java
> +                log.debug("JWT Token has expired");
로깅 레벨을 뭘로 할지가 항상 고민되는데요. 어떤 기준으로 debug를 사용하셨나요?

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/common/oauth2/OAuth2AuthenticationSuccessHandler.java
> +        Authentication authentication) {
```suggestion
    protected String determineTargetUrl(
        HttpServletRequest request, 
        HttpServletResponse response,
        Authentication authentication
    ) {
```

길어서 내려간거 같은데 그냥 다 내려버리죠!

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> +
이 부분은 이미 develop에 있는 부분인데 pr 생성시 문제는 없었나요?

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/controller/UserController.java
> +        }
```suggestion
        if (!id.equals(authentication.userId) {
            throw new ForbiddenException("접근할 수 없는 정보입니다.");
        }
        return ResponseEntity.ok(userService.findById(authentication.userId));
```
가드 클러즈를 사용하는건 어떤가요?

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/domain/User.java
> +        checkNotNull(providerId, "providerId must be provided.");
bean validation으로 검증할 수 있지 않나요? 별도 메소드를 사용한 이유가 궁금합니다

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/dto/UserResponse.java
> +@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
getter 대신 이걸 선호하시나요? 🤔

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/dto/UserResponse.java
> +    public UserResponse(Long userId, String username, Long points) {
```suggestion
    private UserResponse(Long userId, String username, Long points) {
```

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/service/UserService.java
>      public User join(OAuth2User oAuth2User, String provider) {
푸글이 작성한 부분이 아니긴 한데, 파티 참여와 용어가 헷갈릴 수 있어 이름 변경이 필요할거 같습니다

2021-12-07 18:01 UTC, sangmin7648 commented on src/main/resources/application.yaml
>    header: token
이건 삭제해도 될것 같습니다!!

2021-12-07 18:01 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/user/UserControllerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
per class로 한 이유가 있나요?

2021-12-07 18:01 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/user/UserControllerTest.java
> +    }
```suggestion
        mockMvc
            .perform(
                get(BASE_URL + "/{id}", userId)
                    .accept(MediaType.APPLICATION_JSON)
            )
            .andExpectAll(
                status().isOk(),
                handler().handlerType(UserController.class),
                handler().methodName("getUserDetail"),
                jsonPath("$.userId").value(userId),
                jsonPath("$.username").value("테스트 유저1"),
                jsonPath("$.points").value(0)
            )
            .andDo(print());
    }
```

저는 이런 포멧팅을 선호하는데 어떤가요? 🤗🤗

2021-12-07 18:03 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/service/UserService.java
>      public User join(OAuth2User oAuth2User, String provider) {
리팩토링 티켓에 작성해놓을게요. 이 pr에서는 신경 안쓰셔도 될것같습니다

2021-12-08 03:21 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/user/service/UserService.java
> +    public UserResponse findById(Long id) {
네! 변경하겠습니다

2021-12-08 03:28 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/common/jwt/JwtAuthenticationFilter.java
> +                log.debug("JWT Token has expired");
예외처리 윗 부분을 debug로 설정하면서 아무 생각 없이 나머지도 debug로 했네요. IllegaArgument는 error, TokenExpired는 warn으로 설정하는건 어떨까요?

2021-12-08 03:30 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/error/ErrorResponse.java
> +
따로 충돌은 안 나고 있는듯 합니다!

2021-12-08 03:44 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/common/configuration/SwaggerConfiguration.java
> +    }
이 작업은 swagger와 어떤 연관이 있나요?

2021-12-08 03:47 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/common/jwt/JwtAuthenticationFilter.java
> +                log.debug("JWT Token has expired");
TokenExpiredException 의 예외처리를 여기서 한 이유가 있을까요? 제가 알기로는 verify 메서드에서 발생시키는 걸로 알고 있어서여

2021-12-08 03:49 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/user/controller/UserController.java
> +        }
오호 그런 방식을 가드 클러즈라 하는군요 하나 배워갑니다 😁😁

2021-12-08 04:29 UTC, sirin0762 approved these changes
고생하셨습니다!!😁😁 저의 우당탕탕 코드에 푸글이 힘들어한것 같아 미안하네요 ㅠㅠ

2021-12-08 04:46 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/user/domain/User.java
> +        checkNotNull(providerId, "providerId must be provided.");
bean validation에서 메세징이나 길이 제한 등의 기능을 못 할줄 알았는데 다 제공되더라구요! 삭제하고 bean validation으로 통일하겠습니다.

2021-12-08 04:47 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/user/dto/UserResponse.java
> +@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
사용하지 않는 getter setter는 최대한 피하려고 하는 편입니다! 특히 response dto에서 정적 팩토리메서드로 객체 생성을 하고 있어서 더욱 필요가 없을 것 같더라구요!

2021-12-08 05:16 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/common/configuration/SwaggerConfiguration.java
> +    }
이거는 swagger 문서에서 Bearer Token 설정할 수 있도록 하는 부분이에요! 요청 테스트 해볼 때 직접 토큰을 넣을 수 있게 해줍니다😉

2021-12-08 05:17 UTC, suhyunsim commented
> 고생하셨습니다!!gringrin 저의 우당탕탕 코드에 푸글이 힘들어한것 같아 미안하네요 ㅠㅠ

아닙니다~ 로사가 적어주신 내용 바탕으로 해서 수월했어요!!

2021-12-08 05:20 UTC, merged