[MODI-81] 유저 포인트 충전
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #21
Opened 2021-12-09 05:20 UTC by sirin0762

- 포인트 충전 부분의 검증에 대해서 확실한 피드백 주시면 감사하겠습니다.😁😁

2021-12-09 06:25 UTC, sangmin7648 requested changes
charge 라는 단어가 돈에 관련되면 충전이 아니라 요금이 되어버려서 수정이 필요할거 같습니다!

2021-12-09 06:25 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/point/service/PointService.java
> +    public PointAmountDto chargePoints(Long userId, Integer points) {
전기나 배터리 같은 것은 charge가 충전이 되지만 돈 관련되면 charge가 요금이 되어버려서 혼란이 있을 수 있을거 같아요. 다른 이름이 좋을거 같습니다

2021-12-09 06:25 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/user/domain/User.java
> +    public void chargePoints(Integer points) {
요것도 같은 맥락에서 charge가 아닌 다른 동사로 바꾸는게 어떨까요?

2021-12-09 06:25 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/point/dto/PointChargeRequest.java
> +public class PointChargeRequest {
charge!!!

2021-12-09 07:43 UTC, sangmin7648 approved these changes

2021-12-10 01:14 UTC, suhyunsim approved these changes
확인했습니다! 🤓 고생많으셨어요!!

2021-12-10 01:52 UTC, merged