[MODI-186] Ott Response 에 Swagger 추가, OttNameResponse  추가
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #41
Opened 2021-12-13 09:39 UTC by sirin0762

2021-12-13 09:44 UTC, sangmin7648 requested changes

2021-12-13 09:44 UTC, sangmin7648 commented on src/main/resources/db/migration/V2021.12.13.1814__addOttEnglishName.sql
> +ALTER TABLE `otts` ADD `english_name` VARCHAR NOT NULL;
```suggestion
ALTER TABLE `otts` ADD `english_name` VARCHAR(255) NOT NULL;
```

h2에서는 varchar 크기 안줘도 돌아가는데 mysql에서는 오류날거에요 🤣

2021-12-14 03:42 UTC, suhyunsim approved these changes
확인했습니다!🤓

2021-12-14 04:27 UTC, sangmin7648 approved these changes

2021-12-14 04:28 UTC, merged