[MODI-274] REFACTOR : 파티가입시 트랜젝션 관리
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #72
Opened 2021-12-21 08:26 UTC by sirin0762

- DataIntegrationViolationException의 경우, SQLException을 RuntimeException으로 포장하기 위한 DataAceessException에서 파생 된 것이라서 ERROR 로그를 잡지 못했습니다 ㅠ... 차후에 도전해보겠습니다
- 파티 가입 요청을 동일 파티에 계속 할 경우, ERROR 로그가 계속 해서 찍히는 걸 방지하기 위해 과거에 했던 예외처리를 다시 가져왔습니다(마지막 커밋).
- 이러한 기능구현은 처음이라 분명 문제가 많을 듯 합니다. 유심히 봐주시면 감사하겠습니다 ㅠㅠ

2021-12-21 12:36 UTC, sangmin7648 requested changes
> - DataIntegrationViolationException의 경우, SQLException을 RuntimeException으로 포장하기 위한 DataAceessException에서 파생 된 것이라서 ERROR 로그를 잡지 못했습니다 ㅠ... 차후에 도전해보겠습니다
> - 파티 가입 요청을 동일 파티에 계속 할 경우, ERROR 로그가 계속 해서 찍히는 걸 방지하기 위해 과거에 했던 예외처리를 다시 가져왔습니다(마지막 커밋).

이 부분이 아까 Exception으로 캐치해도 에러 로그가 남는 부분 맞나요? 저는 예외를 잡는 문제가 아닌 것으로 이해했었는데 DataAccessException에 대해서 말씀하신 부분이 어떤 것인지 궁금해요 😮

2021-12-21 12:36 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/party/controller/PartyController.java
> +    private final int MAX_ATTEMPT_COUNT = 2;
한 곳에서만 사용한다면 메소드 내에 지역 변수로 두는게 어떨까요?? 🤔
아니면 다른 곳에서도 사용하는 경우가 있을까요?

2021-12-21 12:36 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/party/controller/PartyController.java
> +        int requestCount = 0;
요청과 의미가 헷갈릴 수 있을거 같아요. 상수와 비슷하게 `attemptCount`는 어떤가요?

2021-12-21 12:36 UTC, sangmin7648 commented on src/main/resources/db/migration/V2021.12.20.2207__addVersionInParty.sql
> +    ADD `version` INT NOT NULL;
메인에 머지되기 이전에 스키마 변경이 필요할거 같은데요. hinbernate.ddl-auto의 validate가 엔티티에 없는 필드가 DB에 있는 경우 어떻게 되는지 알아봐야겠네요. 혹시 아신다면 댓글 남겨주세요!

2021-12-21 12:36 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
> +        Long partyId = 5L;
executorService를 사용해 동시성 테스트를 해 낙관적 락이 정상작동하는지 테스트 해볼 수 있을 것 같습니다

2021-12-22 04:15 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/party/controller/PartyController.java
> +    private final int MAX_ATTEMPT_COUNT = 2;
혹시 다른 곳에서 사용할 수도 있다고 판단해서 이렇게 짰습니다 ㅎㅎ
수정해볼게여~!

2021-12-22 04:15 UTC, sirin0762 commented on src/main/java/com/prgrms/modi/party/controller/PartyController.java
> +        int requestCount = 0;
오 좋습니다!!

2021-12-22 05:20 UTC, suhyunsim approved these changes

2021-12-22 14:10 UTC, sangmin7648 approved these changes

2021-12-22 17:22 UTC, merged