[MODI-73] 전체 Ott 목록 조회 api
prgrms-web-devcourse/Team_MODI_MODI_BE pull request #8
Opened 2021-12-04 06:43 UTC by sirin0762

- 피드백은 언제나 환영입니다!!

2021-12-05 08:20 UTC, sangmin7648 requested changes
첫 진짜 리뷰네요 ㅋㅋㅋㅋ ㅎㅇㅌ!!!

2021-12-05 08:20 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/ott/dto/OttResponse.java
> +    }
저는 정적 팩토리 메소드로 처리했는데 이부분 맞춰보면 좋을거 같아요

2021-12-05 08:20 UTC, sangmin7648 commented on src/main/resources/application.yaml
> +      tracking-modes: cookie
뭐를 위한 설정인가요?? 🤔🤔

2021-12-05 08:20 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
> +            .build();
`@AutoConfigureMockMvc` 해서만 사용해봤는데 요거는 어떤 설정인가요?

2021-12-05 08:20 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
> +    }
200 인지 확인하는거 이외에도 값에 대한 체크도 조금 해주는게 좋을거 같습니다 👍

2021-12-05 08:20 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
> +    ObjectMapper objectMapper;
요거 필요한가요?

2021-12-05 15:47 UTC, sangmin7648 approved these changes

2021-12-05 15:47 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
이건 왜 per_class로 설정하셨나요?

2021-12-05 15:47 UTC, sangmin7648 requested changes

2021-12-05 15:47 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
이건 왜 per_class로 설정하셨나요?

2021-12-05 22:12 UTC, suhyunsim requested changes
고생하셨습니다!
공식적인 첫 PR이다보니 서로 통일할 요소들이 많이 보이네요🤓🤓
오늘 팀 회의 때 다같이 논의해봅시다😉

2021-12-05 22:12 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
> +    @GetMapping()
`()` 사용하지 않으면 빼는 것도 좋을 것 같아요!

2021-12-05 22:12 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
> +    public ResponseEntity<AllOttListResponse> getAllOtts() {
AllOttListResponse와 OttResponse를 둘 다 만들어서 사용하는 이유가 있을까요?

2021-12-05 22:12 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/domain/OTT.java
> +    protected OTT() {
다같이 얘기해볼 사항인데 `OTT`, `Ott`, `ott` 등 여러 가지 표현 중에 하나로 통일하는게 깔끔해보일 것 같습니다!

2021-12-05 22:12 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/domain/OTT.java
> +        this.monthlyFee = monthlyFee;
구독료와 월별요금을 인원으로 나누는 책임을 OTT객체가 갖도록 해야 할까요? 아니면 OTT를 생성할 때 값을 아예 입력받는 것이 좋을까요?🤔

2021-12-05 22:12 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/service/OttService.java
> +        return new AllOttListResponse(ottRepository.findAll().stream()
dto를 어떤 레이어까지 사용할지 팀에서 논의하면 좋겠습니다!

2021-12-05 22:12 UTC, suhyunsim commented on src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
> +            .build();
제가 전에 사용한 코드를 참고하신거라면 아마도 한글 깨짐 오류를 수정하기 위한 설정일 것 같아요!

2021-12-05 22:22 UTC, suhyunsim commented on src/main/java/com/prgrms/modi/ott/domain/OTT.java
> +        this.monthlyFee = monthlyFee;
OTT객체에 대한 단위테스트도 추가되면 좋을 것 같아요

2021-12-06 03:09 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
> +    public ResponseEntity<AllOttListResponse> getAllOtts() {
이부분 놓쳤네요 ㅋㅋㅋ List<OttResponse>는 어떤가요?

2021-12-06 03:12 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/ott/domain/OTT.java
> +        this.monthlyFee = monthlyFee;
@suhyunsim  OTT가 값만 있고 동작이 아직 없다보니 단위 테스트가 필요한가? 하는 생각이 들었습니다. bean validation도 spring data jpa 쿼리 메소드처럼 믿고 가야할까요 아니면 테스트를 해야할까요? 저는 개인적으로 커스텀 validator를 작성했을때만 검정 테스트 하는게 어떨까 생각합니다

2021-12-06 03:13 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/ott/service/OttService.java
> +        return new AllOttListResponse(ottRepository.findAll().stream()
저도 이부분 많이 보민됩니다. 같이 얘기 해봐요

2021-12-06 07:42 UTC, sangmin7648 approved these changes

2021-12-06 07:42 UTC, sangmin7648 commented on src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
> +public class OttRestController {
요것도 컨벤션 정해야겠군요. 리팩토리 티켓에 남겨놓겠습니다 일단은 넘어가요

2021-12-06 07:42 UTC, sangmin7648 commented on src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
> +    public static OTT getOttFixture(Long id) {
이거 static일 필요가 있나요?

2021-12-07 03:52 UTC, suhyunsim approved these changes

2021-12-07 04:33 UTC, merged